FROM mambaorg/micromamba:1.2.0

LABEL maintainer="ECDC microbiology ecdc.microbiology@ecdc.europa.eu"
# container name: fastani
LABEL version="1.34"

USER root
RUN apt-get update && apt-get install -y procps

USER $MAMBA_USER
RUN micromamba create -n fastani

RUN micromamba install -n fastani python=3.10 pandas=2.2.3 fastani=1.34 -c bioconda -c conda-forge

RUN micromamba clean --all --yes

ENV PATH /opt/conda/envs/fastani/bin:$PATH
